# Generated by Django 4.2.5 on 2023-09-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbooking',
            name='Round_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='airbooking',
            name='round_To',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='airbooking',
            name='round_travel_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
