# Generated by Django 4.2.5 on 2023-09-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_airbooking_round_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbooking',
            name='No_of_passeengers',
            field=models.IntegerField(default=1),
        ),
    ]
